import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/header'

const inter = Inter({ subsets: ['latin'] })
import roofingCoverImage from '../assets/images/roofingCoverImage.webp'
import Image from 'next/image'
import Footer from './components/footer/footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='font-main' lang="en">
      <body className={`min-h-screen h-full w-full flex flex-col  items-center bg-white text-jet`}>
        <div className='h-[800px] w-full absolute top-0 bg-blue-950 bg-opacity-60 -z-10'></div>
        <Image className='h-[800px] w-full object-cover opacity-50 absolute top-0 grayscale -z-20' src={roofingCoverImage} alt=''/>
        <Header/>
        <main className='flex flex-col w-full h-full max-w-7xl grow '>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
//not sure if i like the green color for the theme..