import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='font-main' lang="en">
      <body className={`min-h-screen h-full w-full flex flex-col gap-4 items-center bg-white`}>
        <Header/>
        <main className='max-w-7xl h-full w-full grow flex flex-col'>{children}</main>
        
      </body>
    </html>
  )
}
//not sure if i like the green color for the theme..